name: sample
root: ./

windows:
  - editor:
      layout:  tiled
      # Synchronize all panes of this window, can be enabled before or after the pane commands run.
      # 'before' represents legacy functionality and will be deprecated in a future release, in favour of 'after'
      # synchronize: after
      panes:
        - zsh
        - cargo run --bin server
        - cargo run --bin client
        - cargo run --bin client

